### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by gusennan** [donaldlab/osprey-gui#13]
4 out of 5 times that I've tried to compile the peptide conformation space (attached), this index out of bounds exception is thrown. I generated this confspace by splitting the 6sa8 PDB and saving the peptide.
[6sa8-b.confspace.tar.gz](https://github.com/donaldlab/osprey-gui/files/4955665/6sa8-b.confspace.tar.gz)

```
java.lang.IndexOutOfBoundsException: Index 224 out of bounds for length 219
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:426)
	at edu.duke.cs.molscope.molecule.Molecule$Atoms.get(Molecule.kt)
	at edu.duke.cs.molscope.molecule.Molecule$Atoms.get(Molecule.kt:57)
	at edu.duke.cs.molscope.view.BallAndStick$cylinders$1.fillVertexBuffer(BallAndStick.kt:132)
	at edu.duke.cs.molscope.render.CylinderRenderer$Entry.update(CylinderRenderer.kt:143)
	at edu.duke.cs.molscope.render.CylinderRenderer.update(CylinderRenderer.kt:173)
	at edu.duke.cs.molscope.render.SlideRenderer.render(SlideRenderer.kt:482)
	at edu.duke.cs.molscope.gui.SlideWindow.render(SlideWindow.kt:135)
	at edu.duke.cs.molscope.gui.WindowCore.render$molscope(Window.kt:285)
	at edu.duke.cs.molscope.gui.Window.render(Window.kt:58)
	at edu.duke.cs.ospreygui.MainKt.main(main.kt:69)
	at edu.duke.cs.ospreygui.MainKt.main(main.kt)
```

**Comment by cuchaz** [comment]
I think I've run into this one before. Here's a temporary workaround. Just comment out [this line](https://github.com/donaldlab/osprey-gui/blob/master/src/main/kotlin/edu/duke/cs/ospreygui/features/slide/CompileConfSpace.kt#L358)

I'm considering taking out the fancy rendering effects when compiling anyway. Synchronizing the renderer with the molecule while compiling is a big pain in the butt. There's races everywhere, which probably is what's causing this error. Also, having to use a single molecule instance for each mutation means we have to serialize all the mutations, which limits opportunities for parallelism.

Optimizing the conf space compiler is one of the things on my todo list.

**Comment by gusennan** [comment]
Thanks, that seems to have done it.  I'll put in a PR with that temporary change.

**Comment by gusennan** [comment]
Temporary resolution in c91db809f0f253ede93b85f1d54b01a42c39845c.
